<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>277</X>
  <Y>878</Y>
  <VerticalWidth>252</VerticalWidth>
  <VerticalHeight>50</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>00000000</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>09FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>26FFFFFF</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF29CC54</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF70CC89</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC7870</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC3729</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FF7A7A7A</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAdDYWxpYnJpAAAvQgX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>SolidColor</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>False</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>EnderLilies.Randomizer.dll</Path>
      <Settings>
        <FilePath>Components/EnderLilies.Randomizer.json</FilePath>
        <ExePath>F:\SteamLibrary\steamapps\common\ENDER LILIES\EnderLilies\Binaries\Win64\EnderLiliesSteam-Win64-Shipping.exe</ExePath>
        <ShuffleAmulets>True</ShuffleAmulets>
        <ShuffleBlights>True</ShuffleBlights>
        <ShuffleChains>True</ShuffleChains>
        <ShuffleFindings>True</ShuffleFindings>
        <ShuffleRelics>True</ShuffleRelics>
        <ShuffleEnemies>False</ShuffleEnemies>
        <ShuffleSpirits>True</ShuffleSpirits>
        <ShuffleTablets>True</ShuffleTablets>
        <ShuffleWishes>True</ShuffleWishes>
        <ShuffleSlots>True</ShuffleSlots>
        <UnusedRelics>True</UnusedRelics>
        <UATServer>True</UATServer>
        <NGPlus>False</NGPlus>
        <Seed>330557669</Seed>
        <SkinOverride>0</SkinOverride>
        <StartChapter>0</StartChapter>
        <MaxChapter>9</MaxChapter>
        <ShuffleRooms>False</ShuffleRooms>
        <StartingSpirits>31</StartingSpirits>
        <MetaProgression>False</MetaProgression>
        <MinibossesChapter>False</MinibossesChapter>
        <DashProgressive>True</DashProgressive>
        <StartWeaponUsesAncientSouls>False</StartWeaponUsesAncientSouls>
        <ShuffleWeaponUpgrades>True</ShuffleWeaponUpgrades>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>50</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>1.23</TimerFormat>
        <OverrideSplitColors>False</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FFAAAAAA</TimerColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
  </Components>
</Layout>